name: 'Benchmark Check'


on:
  workflow_dispatch:

  push:


env:
  PATH_BENCHMARK_PROJECT: 'tests/Demo.Benchmarks/Demo.Benchmarks.csproj'


jobs:

  benchmark-check:
    name: 'Benchmark Check'
    runs-on: 'ubuntu-latest'

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '9.x.x'

    - name: 'Restore previous benchmark reports'
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/previous-benchmark-reports
        key: benchmark-reports-cached

    - name: 'Restore .NET Tools'
      run: dotnet tool restore

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build projects'
      run: dotnet build -c Release --no-restore ${{ github.workspace }}/${{ env.PATH_BENCHMARK_PROJECT }}

    - name: 'Run benchmarks'
      run: dotnet run -p ${{ github.workspace }}/${{ env.PATH_BENCHMARK_PROJECT }} -c Release

    - name: 'List benchmark reports'
      run: |
        pwd
        ls -la ${{ github.workspace }}/BenchmarkDotNet.Artifacts
        echo "-----"
        ls -la ${{ github.workspace }}/BenchmarkDotNet.Artifacts/results


    # - name: 'List previous benchmark reports'
    #   if: always()
    #   run: |
    #     pwd
    #     ls -la ${{ github.workspace }}/previous-benchmark-reports
