name: 'Benchmark Check'


on:
  workflow_dispatch:

  push:


env:
  PATH_BENCHMARK_PROJECT: 'tests/Demo.Benchmarks/Demo.Benchmarks.csproj'
  DIR_PREVIOUS_BENCHMARK_REPORTS: 'previous-benchmark-reports'
  DIR_OUTPUT_BENCHMARK_REPORTS: 'BenchmarkDotNet.Artifacts/results'
  DIR_OUTPUT_COMPARE_REPORT: 'BenchmarkReporter'


jobs:

  benchmark-check:
    name: 'Benchmark Check'
    runs-on: 'ubuntu-latest'

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '9.x.x'

    - name: 'Restore previous benchmark reports'
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/${{ env.DIR_PREVIOUS_BENCHMARK_REPORTS }}
        key: benchmark-reports-cached

    - name: 'Restore .NET Tools'
      run: dotnet tool restore

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build projects'
      run: dotnet build -c Release --no-restore ${{ github.workspace }}/${{ env.PATH_BENCHMARK_PROJECT }}

    - name: 'Run benchmarks'
      run: dotnet run -p ${{ github.workspace }}/${{ env.PATH_BENCHMARK_PROJECT }} -c Release

    - name: 'Check if exists previous benchmark reports'
      id: check_previous_reports
      run: |
        if [ -d "${{ github.workspace }}/${{ env.DIR_PREVIOUS_BENCHMARK_REPORTS }}" ]; then
          echo "Previous benchmark reports found."
          echo "previous-benchmark-reports-exists=true" >> $GITHUB_OUTPUT
        else
          echo "No previous benchmark reports found."
          echo "previous-benchmark-reports-exists=false" >> $GITHUB_OUTPUT

    - name: 'Run benchmarks compare'
      if: steps.check_previous_reports.outputs.previous-benchmark-reports-exists == 'true'
      run: dotnet pbreporter compare -b ${{ github.workspace }}/${{ env.DIR_PREVIOUS_BENCHMARK_REPORTS }} -t ${{ github.workspace }}/${{ env.DIR_OUTPUT_BENCHMARK_REPORTS }} -f console -f markdown -f json

      # - name: 'List benchmark reports'
    #   run: |
    #     pwd
    #     ls -la ${{ github.workspace }}/BenchmarkDotNet.Artifacts
    #     echo "-----"
    #     ls -la ${{ github.workspace }}/BenchmarkDotNet.Artifacts/results


    # - name: 'List previous benchmark reports'
    #   if: always()
    #   run: |
    #     pwd
    #     ls -la ${{ github.workspace }}/previous-benchmark-reports
