name: 'Benchmarks Check - Full Example'


on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
    - main


env:
  PATH_BENCHMARKS_PROJECT: 'tests/Demo.Benchmarks/Demo.Benchmarks.csproj'
  DIR_BASELINE_REPORTS: 'baseline-benchmarks-reports'
  DIR_TARGET_REPORTS: 'BenchmarkDotNet.Artifacts/results'
  DIR_COMPARE_REPORTS: 'BenchmarkReporter'
  CACHE_KEY: 'baseline-benchmarks-reports-full-example'
  THRESHOLD_MEAN: 5%
  THRESHOLD_ALLOCATION: 5%



jobs:
  benchmarks-check-full-example:
    name: 'Benchmarks Check - Full Example'
    runs-on: 'ubuntu-latest'
    permissions:
      pull-requests: write

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4.2.2

    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '9.x.x'

    - name: 'Restore Baseline benchmark reports'
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }}
        key: ${{ env.CACHE_KEY }}

    - name: 'Baseline benchmark reports found'
      run: |
        echo "Cache restored: ${{ steps.cache.outputs.cache-matched-key != '' }}"

    - name: 'Install PowerUtils.BenchmarkDotnet.Reporter'
      if: steps.cache.outputs.cache-matched-key != ''
      run: dotnet tool install --global PowerUtils.BenchmarkDotnet.Reporter

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build projects'
      run: dotnet build -c Release --no-restore ${{ github.workspace }}/${{ env.PATH_BENCHMARKS_PROJECT }}

    - name: 'Run benchmarks'
      run: dotnet run -p ${{ github.workspace }}/${{ env.PATH_BENCHMARKS_PROJECT }} -c Release

    - name: 'Run benchmarks compare'
      if: steps.cache.outputs.cache-matched-key != ''
      run: pbreporter compare -b ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }} -t ${{ github.workspace }}/${{ env.DIR_TARGET_REPORTS }} -f console -f markdown -f json -tm ${{ env.THRESHOLD_MEAN }} -ta ${{ env.THRESHOLD_ALLOCATION }} -ft -fw

    - name: 'Move target reports to baseline'
      run: |
        echo "Moving target reports to baseline reports"
        rm -rf ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }}
        mv ${{ github.workspace }}/${{ env.DIR_TARGET_REPORTS }} ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }}

    - name: 'Save current benchmark reports for next run'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }}
        key: ${{ env.CACHE_KEY }}-${{ github.run_number }}

    - name: 'Upload benchmark reports'
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: 'benchmark-reports'
        path: ${{ github.workspace }}/${{ env.DIR_BASELINE_REPORTS }}/*
        if-no-files-found: error

    - name: 'Upload compare benchmark report'
      uses: actions/upload-artifact@v4.6.2
      if: steps.cache.outputs.cache-matched-key != '' && always()
      with:
        name: 'benchmark-comparison-reports'
        path: ${{ github.workspace }}/${{ env.DIR_COMPARE_REPORTS }}/*
        if-no-files-found: error

    - name: 'Add compare benchmark report in PR Comment'
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request' && steps.cache.outputs.cache-matched-key != '' && always()
      with:
        header: compare-benchmark-report
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        path: ${{ github.workspace }}/${{ env.DIR_COMPARE_REPORTS }}/benchmark-comparison-report.md

    - name: 'Publish benchmark report in Summary'
      if: steps.cache.outputs.cache-matched-key != '' && always()
      run: cat ${{ github.workspace }}/${{ env.DIR_COMPARE_REPORTS }}/benchmark-comparison-report.md > $GITHUB_STEP_SUMMARY
