name: 'Benchmark Check'


on:
  workflow_dispatch:
    inputs:
      value:
        description: "Value 1"
        required: true
        type: string

  push:


env:
  CACHE_KEY: 'cache-benchmark-reports'


jobs:
  benchmark-check:
    name: 'Benchmark Check'
    runs-on: 'ubuntu-latest'

    steps:
    - name: "Cache file"
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/test
        key: my-cache-key-1

    - name: "Read file"
      run: |
        cd ${{ github.workspace }}/test
        pwd
        ls -la ${{ github.workspace }}/test
        cat ${{ github.workspace }}/test/file.txt

# ############################

    - name: "Writer file"
      run: |
        mkdir -p ${{ github.workspace }}/test
        echo ${{ github.event.inputs.value }} > "${{ github.workspace }}/test/file.txt"
        pwd
        ls -la ${{ github.workspace }}/test
        cat ${{ github.workspace }}/test/file.txt

    - name: "Cache file"
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/test
        key: my-cache-key-1-${{ github.run_number }}
