name: 'Benchmark Check'

on:
  workflow_dispatch:

  push:


env:
  MY_ENV_VAR: 'my-env-var-1'
  CACHE_KEY: 'my-cache-key-2'


jobs:
  benchmark-check:
    name: 'Benchmark Check'
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Cache file'
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/test
        key: ${{ env.CACHE_KEY }}

    - name: 'Read file'
      run: |
        cd ${{ github.workspace }}/test
        pwd
        ls -la ${{ github.workspace }}/test
        cat ${{ github.workspace }}/test/file.txt

# ############################

    - name: 'Writer file'
      run: |
        mkdir -p ${{ github.workspace }}/test1
        echo ${{ env.MY_ENV_VAR }} > "${{ github.workspace }}/test1/file1.txt"
        pwd
        ls -la ${{ github.workspace }}/test1
        echo "--->"
        cat ${{ github.workspace }}/test1/file1.txt

    - name: 'Cache file'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/test1
        key: ${{ env.CACHE_KEY }}-${{ github.run_number }}
